package main

// Preset provider definitions (35 platforms).
// These serve as defaults when no user config exists.

var presetProviders = []Provider{
	{
		ID: "openai", Name: "OpenAI", Type: "openai_compatible",
		BaseURL: "https://api.openai.com/v1",
		Priority: 10,
		Description: "OpenAI 官方 API",
		Icon: "openai",
		Models: []ModelDef{
			{ID: "gpt-4o", Name: "GPT-4o", Enabled: true},
			{ID: "gpt-4o-mini", Name: "GPT-4o Mini", Enabled: true},
			{ID: "o1", Name: "o1", Enabled: true},
			{ID: "o3", Name: "o3", Enabled: true},
			{ID: "o4-mini", Name: "o4-mini", Enabled: true},
		},
	},
	{
		ID: "deepseek", Name: "DeepSeek", Type: "openai_compatible",
		BaseURL: "https://api.deepseek.com/v1",
		Priority: 5,
		Description: "深度求索 - 高性价比国产大模型",
		Icon: "deepseek",
		Models: []ModelDef{
			{ID: "deepseek-chat", Name: "DeepSeek Chat (V3)", Enabled: true},
			{ID: "deepseek-reasoner", Name: "DeepSeek Reasoner (R1)", Enabled: true},
		},
	},
	{
		ID: "qwen", Name: "通义千问", Type: "openai_compatible",
		BaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
		Priority: 5,
		Description: "阿里云通义千问",
		Icon: "qwen",
		Models: []ModelDef{
			{ID: "qwen-turbo", Name: "Qwen Turbo", Enabled: true},
			{ID: "qwen-plus", Name: "Qwen Plus", Enabled: true},
			{ID: "qwen-max", Name: "Qwen Max", Enabled: true},
			{ID: "qwen-long", Name: "Qwen Long", Enabled: true},
		},
	},
	{
		ID: "tokenhub-coding", Name: "腾讯 TokenHub Coding Plan", Type: "openai_compatible",
		BaseURL: "https://api.lkeap.cloud.tencent.com/coding/v3",
		Priority: 3,
		Description: "腾讯 TokenHub 编程套餐（按请求次数，5h/周/月限额），API Key 格式 sk-sp-xxxx",
		Icon: "hunyuan",
		APIKeyURL: "https://console.cloud.tencent.com/tokenhub/codingplan",
		Models: []ModelDef{
			{ID: "tc-code-latest", Name: "Auto 智能路由", Enabled: true},
			{ID: "glm-5", Name: "GLM-5", Enabled: true},
			{ID: "minimax-m2.5", Name: "MiniMax M2.5", Enabled: true},
			{ID: "kimi-k2.5", Name: "Kimi K2.5", Enabled: true},
		},
	},
	{
		ID: "tokenhub-plan", Name: "腾讯 TokenHub Token Plan", Type: "openai_compatible",
		BaseURL: "https://api.lkeap.cloud.tencent.com/plan/v3",
		Priority: 3,
		Description: "腾讯 TokenPlan 个人版（按 Token 计费，订阅制），API Key 格式 sk-tp-xxxx",
		Icon: "hunyuan",
		APIKeyURL: "https://console.cloud.tencent.com/tokenhub/tokenplan",
		Models: []ModelDef{
			{ID: "tc-code-latest", Name: "Auto 智能路由", Enabled: true},
			{ID: "glm-5", Name: "GLM-5", Enabled: true},
			{ID: "glm-5.1", Name: "GLM-5.1", Enabled: true},
			{ID: "minimax-m2.5", Name: "MiniMax M2.5", Enabled: true},
			{ID: "minimax-m2.7", Name: "MiniMax M2.7", Enabled: true},
			{ID: "kimi-k2.5", Name: "Kimi K2.5", Enabled: true},
			{ID: "deepseek-v4-flash-202605", Name: "DeepSeek V4 Flash 原厂直供", Enabled: true},
			{ID: "deepseek-v4-pro-202606", Name: "DeepSeek V4 Pro 原厂直供", Enabled: true},
			{ID: "hy3-preview", Name: "Hy3 Preview (混元)", Enabled: true},
		},
	},
	{
		ID: "tokenhub-enterprise", Name: "腾讯 TokenHub 企业版", Type: "openai_compatible",
		BaseURL: "https://tokenhub.tencentmaas.com/plan/v3",
		Priority: 3,
		Description: "腾讯 TokenPlan 企业版（积分制，多 Key 配额管理，团队共享）",
		Icon: "hunyuan",
		APIKeyURL: "https://console.cloud.tencent.com/tokenhub/tokenplan-e",
		Models: []ModelDef{
			{ID: "auto", Name: "Auto 智能路由", Enabled: true},
			{ID: "glm-5", Name: "GLM-5", Enabled: true},
			{ID: "glm-5.1", Name: "GLM-5.1", Enabled: true},
			{ID: "glm-5.2", Name: "GLM-5.2", Enabled: true},
			{ID: "glm-5-turbo", Name: "GLM-5 Turbo", Enabled: true},
			{ID: "minimax-m2.5", Name: "MiniMax M2.5", Enabled: true},
			{ID: "minimax-m2.7", Name: "MiniMax M2.7", Enabled: true},
			{ID: "minimax-m3", Name: "MiniMax M3", Enabled: true},
			{ID: "kimi-k2.5", Name: "Kimi K2.5", Enabled: true},
			{ID: "kimi-k2.6", Name: "Kimi K2.6", Enabled: true},
			{ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash", Enabled: true},
			{ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro", Enabled: true},
			{ID: "deepseek-v4-flash-202605", Name: "DeepSeek V4 Flash 原厂直供", Enabled: true},
			{ID: "deepseek-v4-pro-202606", Name: "DeepSeek V4 Pro 原厂直供", Enabled: true},
		},
	},
	{
		ID: "zhipu", Name: "智谱AI", Type: "openai_compatible",
		BaseURL: "https://open.bigmodel.cn/api/paas/v4",
		Priority: 5,
		Description: "智谱清言 GLM 系列",
		Icon: "zhipu",
		Models: []ModelDef{
			{ID: "glm-4-plus", Name: "GLM-4 Plus", Enabled: true},
			{ID: "glm-4", Name: "GLM-4", Enabled: true},
			{ID: "glm-4-flash", Name: "GLM-4 Flash (免费)", Enabled: true},
			{ID: "glm-4v-plus", Name: "GLM-4V Plus (视觉)", Enabled: true},
		},
	},
	{
		ID: "moonshot", Name: "Moonshot (Kimi)", Type: "openai_compatible",
		BaseURL: "https://api.moonshot.cn/v1",
		Priority: 5,
		Description: "月之暗面 Kimi",
		Icon: "moonshot",
		Models: []ModelDef{
			{ID: "moonshot-v1-8k", Name: "Moonshot V1 8K", Enabled: true},
			{ID: "moonshot-v1-32k", Name: "Moonshot V1 32K", Enabled: true},
			{ID: "moonshot-v1-128k", Name: "Moonshot V1 128K", Enabled: true},
		},
	},
	{
		ID: "lingyiwanwu", Name: "零一万物", Type: "openai_compatible",
		BaseURL: "https://api.lingyiwanwu.com/v1",
		Priority: 5,
		Description: "零一万物 Yi 系列",
		Icon: "yi",
		Models: []ModelDef{
			{ID: "yi-large", Name: "Yi Large", Enabled: true},
			{ID: "yi-medium", Name: "Yi Medium", Enabled: true},
			{ID: "yi-vision", Name: "Yi Vision", Enabled: true},
			{ID: "yi-large-turbo", Name: "Yi Large Turbo", Enabled: true},
		},
	},
	{
		ID: "minimax", Name: "MiniMax", Type: "openai_compatible",
		BaseURL: "https://api.minimax.chat/v1",
		Priority: 5,
		Description: "MiniMax 大模型",
		Icon: "minimax",
		Models: []ModelDef{
			{ID: "MiniMax-Text-01", Name: "MiniMax Text 01", Enabled: true},
			{ID: "abab6.5s-chat", Name: "abab6.5s Chat", Enabled: true},
		},
	},
	{
		ID: "siliconflow", Name: "硅基流动", Type: "openai_compatible",
		BaseURL: "https://api.siliconflow.cn/v1",
		Priority: 5,
		Description: "硅基流动 - 开源模型聚合平台",
		Icon: "siliconflow",
		Models: []ModelDef{
			{ID: "Qwen/Qwen2.5-72B-Instruct", Name: "Qwen2.5 72B", Enabled: true},
			{ID: "deepseek-ai/DeepSeek-V3", Name: "DeepSeek V3", Enabled: true},
			{ID: "deepseek-ai/DeepSeek-R1", Name: "DeepSeek R1", Enabled: true},
			{ID: "meta-llama/Llama-3.3-70B-Instruct", Name: "Llama 3.3 70B", Enabled: true},
		},
	},
	{
		ID: "groq", Name: "Groq", Type: "openai_compatible",
		BaseURL: "https://api.groq.com/openai/v1",
		Priority: 5,
		Description: "Groq - 超快推理速度",
		Icon: "groq",
		Models: []ModelDef{
			{ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B", Enabled: true},
			{ID: "llama-3.1-8b-instant", Name: "Llama 3.1 8B", Enabled: true},
			{ID: "mixtral-8x7b-32768", Name: "Mixtral 8x7B", Enabled: true},
			{ID: "gemma2-9b-it", Name: "Gemma 2 9B", Enabled: true},
		},
	},
	{
		ID: "xai", Name: "xAI (Grok)", Type: "openai_compatible",
		BaseURL: "https://api.x.ai/v1",
		Priority: 5,
		Description: "xAI Grok 系列",
		Icon: "xai",
		Models: []ModelDef{
			{ID: "grok-2-latest", Name: "Grok 2", Enabled: true},
			{ID: "grok-3", Name: "Grok 3", Enabled: true},
			{ID: "grok-3-mini", Name: "Grok 3 Mini", Enabled: true},
		},
	},
	{
		ID: "together", Name: "Together AI", Type: "openai_compatible",
		BaseURL: "https://api.together.xyz/v1",
		Priority: 5,
		Description: "Together AI - 开源模型推理平台",
		Icon: "together",
		Models: []ModelDef{
			{ID: "meta-llama/Llama-3.3-70B-Instruct-Turbo", Name: "Llama 3.3 70B Turbo", Enabled: true},
			{ID: "deepseek-ai/DeepSeek-V3", Name: "DeepSeek V3", Enabled: true},
		},
	},
	{
		ID: "mistral", Name: "Mistral AI", Type: "openai_compatible",
		BaseURL: "https://api.mistral.ai/v1",
		Priority: 5,
		Description: "Mistral AI - 欧洲领先大模型",
		Icon: "mistral",
		Models: []ModelDef{
			{ID: "mistral-large-latest", Name: "Mistral Large", Enabled: true},
			{ID: "mistral-small-latest", Name: "Mistral Small", Enabled: true},
			{ID: "codestral-latest", Name: "Codestral", Enabled: true},
			{ID: "open-mistral-nemo", Name: "Mistral Nemo", Enabled: true},
		},
	},
	{
		ID: "doubao", Name: "火山引擎(豆包)", Type: "openai_compatible",
		BaseURL: "https://ark.cn-beijing.volces.com/api/v3",
		Priority: 5,
		Description: "字节跳动火山引擎豆包",
		Icon: "doubao",
		Models: []ModelDef{
			{ID: "doubao-pro-32k", Name: "豆包 Pro 32K", Enabled: true},
			{ID: "doubao-lite-32k", Name: "豆包 Lite 32K", Enabled: true},
		},
	},
	{
		ID: "spark", Name: "讯飞星火", Type: "openai_compatible",
		BaseURL: "https://spark-api-open.xf-yun.com/v1",
		Priority: 5,
		Description: "科大讯飞星火大模型",
		Icon: "spark",
		Models: []ModelDef{
			{ID: "general", Name: "讯飞星火 Lite", Enabled: true},
			{ID: "generalv3.5", Name: "讯飞星火 Pro", Enabled: true},
			{ID: "generalv4", Name: "讯飞星火 Max", Enabled: true},
		},
	},
	{
		ID: "gemini", Name: "Google Gemini", Type: "openai_compatible",
		BaseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
		Priority: 4,
		Description: "Google Gemini - 多模态、超长上下文",
		Icon: "gemini",
		APIKeyURL: "https://aistudio.google.com/apikey",
		Models: []ModelDef{
			{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro", Enabled: true},
			{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash", Enabled: true},
			{ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash", Enabled: true},
			{ID: "gemini-2.0-flash-lite", Name: "Gemini 2.0 Flash Lite", Enabled: true},
			{ID: "gemini-1.5-pro", Name: "Gemini 1.5 Pro", Enabled: true},
			{ID: "gemini-1.5-flash", Name: "Gemini 1.5 Flash", Enabled: true},
		},
	},
	{
		ID: "openrouter", Name: "OpenRouter", Type: "openai_compatible",
		BaseURL: "https://openrouter.ai/api/v1",
		Priority: 20,
		Description: "OpenRouter - 全球模型聚合平台",
		Icon: "openrouter",
		Models: []ModelDef{
			{ID: "openai/gpt-4o", Name: "GPT-4o (via OpenRouter)", Enabled: true},
			{ID: "anthropic/claude-sonnet-4", Name: "Claude Sonnet 4 (via OpenRouter)", Enabled: true},
			{ID: "deepseek/deepseek-chat", Name: "DeepSeek Chat (via OpenRouter)", Enabled: true},
			{ID: "meta-llama/llama-3.3-70b-instruct", Name: "Llama 3.3 70B (via OpenRouter)", Enabled: true},
		},
	},
	{
		ID: "poe", Name: "Poe", Type: "openai_compatible",
		BaseURL: "https://api.poe.com/v1",
		Priority: 15,
		Description: "Poe (Quora) - 多模型聚合平台",
		Icon: "poe",
		Models: []ModelDef{
			{ID: "GPT-4o", Name: "GPT-4o", Enabled: true},
			{ID: "Claude-3.5-Sonnet", Name: "Claude 3.5 Sonnet", Enabled: true},
			{ID: "Gemini-1.5-Pro", Name: "Gemini 1.5 Pro", Enabled: true},
			{ID: "DeepSeek-V3", Name: "DeepSeek V3", Enabled: true},
			{ID: "Llama-3.3-70B", Name: "Llama 3.3 70B", Enabled: true},
		},
	},
	{
		ID: "sid", Name: "SID.ai (开发者平台)", Type: "openai_compatible",
		BaseURL: "https://api.sid.ai/v1",
		Priority: 15,
		Description: "SID.ai 开发者平台 - 兼容 OpenAI API",
		Icon: "sider",
		APIKeyURL: "https://dashboard.sid.ai",
		Models: []ModelDef{
			{ID: "gpt-4o", Name: "GPT-4o", Enabled: true},
			{ID: "gpt-4o-mini", Name: "GPT-4o Mini", Enabled: true},
			{ID: "claude-3-5-sonnet", Name: "Claude 3.5 Sonnet", Enabled: true},
		},
	},
	{
		ID: "sider", Name: "Sider.ai (网页版)", Type: "web_session",
		BaseURL: "https://sider.ai",
		Priority: 2,
		Description: "Sider.ai 网页版聚合平台。Token 填写浏览器登录后的 Session Token（F12→Network→任意请求→Authorization Header）",
		Icon: "sider",
		APIKeyURL: "https://sider.ai",
		Models: []ModelDef{
			// ===== 基础模型 =====
			{ID: "sider", Name: "Sider Fusion", Enabled: true},
			{ID: "gemini-3.5-flash-lite", Name: "Gemini 3.5 Flash Lite", Enabled: true},
			{ID: "gemini-3.5-flash-lite-think", Name: "Gemini 3.5 Flash Lite Think", Enabled: true},
			{ID: "gpt-5.6-luna", Name: "GPT-5.6 Luna", Enabled: true},
			{ID: "gpt-5.6-luna-think", Name: "GPT-5.6 Luna Think", Enabled: true},
			{ID: "glm-5", Name: "GLM-5", Enabled: true},
			{ID: "glm-5-think", Name: "GLM-5 Think", Enabled: true},
			{ID: "gemini-3.0-flash", Name: "Gemini 3.0 Flash", Enabled: true},
			{ID: "gemini-3.0-flash-think", Name: "Gemini 3.0 Flash Think", Enabled: true},
			{ID: "claude-haiku-4.5", Name: "Claude Haiku 4.5", Enabled: true},
			{ID: "claude-haiku-4.5-think", Name: "Claude Haiku 4.5 Think", Enabled: true},
			{ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini", Enabled: true},
			{ID: "deepseek-v4-flash", Name: "DeepSeek-V4-Flash", Enabled: true},
			{ID: "qwen3-max", Name: "Qwen3-Max", Enabled: true},
			// ===== 高级模型 =====
			{ID: "gemini-3.6-flash", Name: "Gemini 3.6 Flash (高级)", Enabled: true},
			{ID: "gemini-3.6-flash-think", Name: "Gemini 3.6 Flash Think (高级)", Enabled: true},
			{ID: "kimi-k3", Name: "Kimi K3 (高级)", Enabled: true},
			{ID: "grok-4.5", Name: "Grok 4.5 (高级)", Enabled: true},
			{ID: "gpt-5.6-terra", Name: "GPT-5.6 Terra (高级)", Enabled: true},
			{ID: "gpt-5.6-terra-think", Name: "GPT-5.6 Terra Think (高级)", Enabled: true},
			{ID: "claude-sonnet-5", Name: "Claude Sonnet 5 (高级)", Enabled: true},
			{ID: "claude-sonnet-5-think", Name: "Claude Sonnet 5 Think (高级)", Enabled: true},
			{ID: "claude-fable-5", Name: "Claude Fable 5 (高级)", Enabled: true},
			{ID: "claude-fable-5-think", Name: "Claude Fable 5 Think (高级)", Enabled: true},
			{ID: "gpt-5.6-sol", Name: "GPT-5.6 Sol (高级)", Enabled: true},
			{ID: "gemini-3.5-flash", Name: "Gemini 3.5 Flash (高级)", Enabled: true},
			{ID: "grok-4.3", Name: "Grok 4.3 (高级)", Enabled: true},
			{ID: "deepseek-v4-pro", Name: "DeepSeek-V4-Pro (高级)", Enabled: true},
			{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash (高级)", Enabled: true},
			{ID: "kimi-k2.5", Name: "Kimi K2.5 (高级)", Enabled: true},
			{ID: "claude-sonnet-4.6", Name: "Claude Sonnet 4.6 (高级)", Enabled: true},
			{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro (高级)", Enabled: true},
			{ID: "gpt-5.1", Name: "GPT-5.1 (高级)", Enabled: true},
			// ===== 超级高级模型 =====
			{ID: "claude-opus-4.8", Name: "Claude Opus 4.8 (超级)", Enabled: true},
			{ID: "claude-opus-4.8-think", Name: "Claude Opus 4.8 Think (超级)", Enabled: true},
		},
		WebSession: &WebSessionConfig{
			LoginURL:    "https://sider.ai",
			APIEndpoint: "https://sider.ai/api/v3/completion/text",
			AuthMode:    "cookie",
			TokenPrefix: "Bearer ",
			ExtraHeaders: map[string]string{
				"Origin":             "chrome-extension://dhoenijjpgpeimemopealfcbiecgceod",
				"User-Agent":         "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
				"Accept":             "text/event-stream",
				"Accept-Language":    "en-US,en;q=0.9",
				"sec-ch-ua":          `\"Not(A:Brand\";v="99", "Google Chrome";v="133", "Chromium";v="133"`,
				"sec-ch-ua-mobile":   "?0",
				"sec-ch-ua-platform": "\"Windows\"",
				"sec-fetch-dest":     "empty",
				"sec-fetch-mode":     "cors",
				"sec-fetch-site":     "cross-site",
				"Referer":            "https://sider.ai/",
			},
			PromptField:  "prompt",
			ModelField:   "model",
			StreamField:  "stream",
			MessageFormat: "prefix_role",
			ExtraBody: map[string]any{
				"app_name":         "ChitChat_Edge_Ext",
				"app_version":      "4.40.0",
				"tz_name":          "Asia/Shanghai",
				"search":           false,
				"auto_search":      false,
				"from":                  "chat",
				"group_id":              "default",
				"cid":                   "",
				"filter_search_history": false,
				"chat_models":           []any{},
				"files":                 []any{},
				"prompt_templates":      []any{},
				"tools":                 map[string]any{"auto": []any{"data_analysis"}},
				"extra_info": map[string]any{
					"origin_url":   "chrome-extension://dhoenijjpgpeimemopealfcbiecgceod/standalone.html",
					"origin_title": "Sider",
				},
			},
			ResponseType: "sse",
			TextPath:     "data.text",
			DoneMarker:   "[DONE]",
		},
	},
	{
		ID: "ollama", Name: "Ollama (本地)", Type: "openai_compatible",
		BaseURL: "http://localhost:11434/v1",
		APIKey: "ollama",
		Priority: 50,
		Description: "本地部署模型",
		Icon: "ollama",
		Models: []ModelDef{
			{ID: "llama3.2", Name: "Llama 3.2", Enabled: true},
			{ID: "qwen2.5", Name: "Qwen 2.5", Enabled: true},
			{ID: "deepseek-r1", Name: "DeepSeek R1", Enabled: true},
		},
	},
	{
		ID: "coze", Name: "扣子 (Coze)", Type: "coze",
		BaseURL: "https://api.coze.cn",
		Priority: 1,
		Description: "扣子智能体平台（专有 API，模型为 coze-{bot_id} 格式）。API Key 填写 PAT 个人访问令牌",
		APIKeyURL:  "https://www.coze.cn",
		Icon: "coze",
		Models: []ModelDef{},
	},
	{
		ID: "nvidia", Name: "NVIDIA NIM", Type: "openai_compatible",
		BaseURL:    "https://integrate.api.nvidia.com/v1",
		Priority:   4,
		Description: "NVIDIA 推理微服务平台，100+ 开源模型免费调用（40 RPM），OpenAI 兼容",
		Icon:        "nvidia",
		APIKeyURL:   "https://build.nvidia.com/",
		Models: []ModelDef{
			{ID: "meta/llama-4-maverick-17b-128e-instruct", Name: "Llama 4 Maverick"},
			{ID: "minimaxai/minimax-m2.7", Name: "MiniMax M2.7"},
			{ID: "deepseek-ai/deepseek-v3.2", Name: "DeepSeek V3.2"},
			{ID: "deepseek-ai/deepseek-r1-distill-llama-8b", Name: "DeepSeek R1 Distill"},
			{ID: "qwen/qwen3.5-397b-a17b", Name: "Qwen 3.5 397B"},
			{ID: "qwen/qwen3-coder-480b", Name: "Qwen3 Coder 480B"},
			{ID: "moonshotai/kimi-k2.6", Name: "Kimi K2.6"},
			{ID: "z-ai/glm-5.1", Name: "GLM 5.1"},
			{ID: "mistralai/mistral-large-3", Name: "Mistral Large 3"},
			{ID: "stepfun-ai/step-3.5-flash", Name: "Step-3.5 Flash"},
			{ID: "nvidia/nemotron-3-nano-30b-a3b", Name: "Nemotron 3 Nano"},
			{ID: "meta/llama-3.1-70b-instruct", Name: "Llama 3.1 70B"},
			{ID: "google/gemma-3n-e4b", Name: "Gemma 3n E4B"},
			{ID: "mistralai/mistral-nemotron", Name: "Mistral Nemotron"},
		},
	},
	{
		ID: "anthropic", Name: "Anthropic Claude", Type: "anthropic",
		BaseURL:    "https://api.anthropic.com",
		Priority:   2,
		Description: "Claude 系列模型（专有 Messages API，系统自动适配）。API Key 填写 Anthropic API Key（sk-ant-xxx）",
		Icon:        "anthropic",
		APIKeyURL:   "https://console.anthropic.com/",
		Models: []ModelDef{
			{ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4"},
			{ID: "claude-3-5-sonnet-20241022", Name: "Claude 3.5 Sonnet"},
			{ID: "claude-3-5-haiku-20241022", Name: "Claude 3.5 Haiku"},
			{ID: "claude-3-opus-20240229", Name: "Claude 3 Opus"},
			{ID: "claude-3-haiku-20240307", Name: "Claude 3 Haiku"},
		},
	},
	{
		ID: "qianfan", Name: "百度千帆", Type: "openai_compatible",
		BaseURL:    "https://qianfan.baidubce.com/v2",
		Priority:   5,
		Description: "百度智能云千帆平台，ERNIE 文心系列 + 第三方模型",
		Icon:        "qianfan",
		APIKeyURL:   "https://qianfan.cloud.baidu.com",
		Models: []ModelDef{
			{ID: "ernie-4.5-turbo-32k", Name: "ERNIE 4.5 Turbo"},
			{ID: "ernie-4.0-turbo-8k", Name: "ERNIE 4.0 Turbo"},
			{ID: "ernie-speed-128k", Name: "ERNIE Speed 128K"},
			{ID: "deepseek-r1-distill-qwen-32b", Name: "DeepSeek R1 Distill Qwen 32B"},
		},
	},
	{
		ID: "novita", Name: "Novita AI", Type: "openai_compatible",
		BaseURL:    "https://api.novita.ai/v3/openai",
		Priority:   5,
		Description: "聚合平台，200+ 开源模型，价格低廉，OpenAI 兼容",
		Icon:        "novita",
		APIKeyURL:   "https://novita.ai/",
		Models: []ModelDef{
			{ID: "deepseek/deepseek-r1", Name: "DeepSeek R1"},
			{ID: "deepseek/deepseek-v3", Name: "DeepSeek V3"},
			{ID: "qwen/qwen-3-235b-a22b", Name: "Qwen 3 235B"},
			{ID: "meta-llama/llama-4-maverick-17b-128e-instruct", Name: "Llama 4 Maverick"},
			{ID: "meta-llama/llama-3.3-70b-instruct", Name: "Llama 3.3 70B"},
		},
	},
	{
		ID: "fireworks", Name: "Fireworks AI", Type: "openai_compatible",
		BaseURL:    "https://api.fireworks.ai/inference/v1",
		Priority:   5,
		Description: "高速推理平台，开源模型优化，OpenAI 兼容",
		Icon:        "fireworks",
		APIKeyURL:   "https://fireworks.ai/account/api-keys",
		Models: []ModelDef{
			{ID: "accounts/fireworks/models/deepseek-v3", Name: "DeepSeek V3"},
			{ID: "accounts/fireworks/models/deepseek-r1", Name: "DeepSeek R1"},
			{ID: "accounts/fireworks/models/qwen3-235b-a22b", Name: "Qwen 3 235B"},
			{ID: "accounts/fireworks/models/llama4-maverick-instruct-basic", Name: "Llama 4 Maverick"},
			{ID: "accounts/fireworks/models/llama-v3p3-70b-instruct", Name: "Llama 3.3 70B"},
		},
	},
	{
		ID: "cohere", Name: "Cohere", Type: "openai_compatible",
		BaseURL:    "https://api.cohere.com/compatibility/v1",
		Priority:   5,
		Description: "企业级 NLP 平台，Command R+ 系列，OpenAI 兼容",
		Icon:        "cohere",
		APIKeyURL:   "https://dashboard.cohere.com/api-keys",
		Models: []ModelDef{
			{ID: "command-r-plus-08-2024", Name: "Command R+"},
			{ID: "command-r-08-2024", Name: "Command R"},
			{ID: "command-a-03-2025", Name: "Command A"},
		},
	},
	{
		ID: "cerebras", Name: "Cerebras", Type: "openai_compatible",
		BaseURL:    "https://api.cerebras.ai/v1",
		Priority:   4,
		Description: "极致推理速度（Llama 系列），适合延迟敏感场景，OpenAI 兼容",
		Icon:        "cerebras",
		APIKeyURL:   "https://cloud.cerebras.ai/",
		Models: []ModelDef{
			{ID: "llama-3.3-70b", Name: "Llama 3.3 70B"},
			{ID: "llama-3.1-8b", Name: "Llama 3.1 8B"},
			{ID: "llama3.1-8b", Name: "Llama 3.1 8B (alt)"},
		},
	},
	{
		ID: "stepfun", Name: "阶跃星辰", Type: "openai_compatible",
		BaseURL:    "https://api.stepfun.com/v1",
		Priority:   5,
		Description: "Step 系列模型，多模态与推理能力均衡，OpenAI 兼容",
		Icon:        "stepfun",
		APIKeyURL:   "https://platform.stepfun.com/",
		Models: []ModelDef{
			{ID: "step-2-16k", Name: "Step-2 16K"},
			{ID: "step-1.5v-mini", Name: "Step-1.5V Mini"},
			{ID: "step-1-128k", Name: "Step-1 128K"},
			{ID: "step-1-8k", Name: "Step-1 8K"},
		},
	},
	{
		ID: "baichuan", Name: "百川智能", Type: "openai_compatible",
		BaseURL:    "https://api.baichuan-ai.com/v1",
		Priority:   5,
		Description: "Baichuan 系列模型，中文能力强，企业场景优化，OpenAI 兼容",
		Icon:        "baichuan",
		APIKeyURL:   "https://platform.baichuan-ai.com/",
		Models: []ModelDef{
			{ID: "Baichuan4-Turbo", Name: "Baichuan 4 Turbo"},
			{ID: "Baichuan4-Air", Name: "Baichuan 4 Air"},
			{ID: "Baichuan4", Name: "Baichuan 4"},
			{ID: "Baichuan3-Turbo", Name: "Baichuan 3 Turbo"},
		},
	},
	{
		ID: "agnes", Name: "Agnes AI", Type: "openai_compatible",
		BaseURL:    "https://apihub.agnes-ai.com/v1",
		Priority:   5,
		Description: "新加坡 Sapiens AI 多模态平台（文本/图像/视频），OpenAI 兼容，注册即送免费额度",
		Icon:        "agnes",
		APIKeyURL:   "https://platform.agnes-ai.com/",
		Models: []ModelDef{
			{ID: "agnes-2.0-flash", Name: "Agnes 2.0 Flash (文本)"},
			{ID: "agnes-image-2.1-flash", Name: "Agnes Image 2.1 Flash (图像)"},
			{ID: "agnes-image-2.0-flash", Name: "Agnes Image 2.0 Flash (图像)"},
			{ID: "agnes-video-v2.0", Name: "Agnes Video V2.0 (视频)"},
		},
	},
	{
		ID: "aihubmix", Name: "AIHubMix", Type: "openai_compatible",
		BaseURL:    "https://aihubmix.com/v1",
		Priority:   5,
		Description: "聚合平台，提供免费额度，OpenAI 兼容 API",
		Icon:        "aihubmix",
		APIKeyURL:   "https://aihubmix.com/",
		Models: []ModelDef{
			{ID: "gpt-4o", Name: "GPT-4o"},
			{ID: "claude-3.5-sonnet", Name: "Claude 3.5 Sonnet"},
			{ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash"},
		},
	},
	{
		ID: "lmstudio-local", Name: "LM Studio (本地)", Type: "openai_compatible",
		BaseURL:    "http://localhost:1234/v1",
		Priority:   1,
		Description: "LM Studio 本地模型推理，OpenAI 兼容 API",
		Icon:        "lmstudio",
		APIKeyURL:   "https://lmstudio.ai/",
		Models: []ModelDef{
			{ID: "local-model", Name: "本地模型（自动加载）"},
		},
	},
	{
		ID: "xfyun-maas", Name: "讯飞星辰MaaS", Type: "openai_compatible",
		BaseURL:    "https://maas-coding-api.cn-huabei-1.xf-yun.com/v2",
		Priority:   5,
		Description: "科大讯飞星辰MaaS平台，OpenAI兼容，支持Qwen/DeepSeek/GLM/Kimi等开源模型",
		Icon:        "xfyun",
		APIKeyURL:   "https://maas.xfyun.cn/packageSubscription",
		Models: []ModelDef{
			{ID: "xsparkx2", Name: "Spark X2", Enabled: true},
			{ID: "xsparkx2flash", Name: "Spark-X2-Flash", Enabled: true},
			{ID: "xopglm52", Name: "GLM-5.2", Enabled: true},
			{ID: "xopglm51", Name: "GLM-5.1", Enabled: true},
			{ID: "xopglm5", Name: "GLM-5", Enabled: true},
			{ID: "xopdeepseekv4pro", Name: "DeepSeek-V4-Pro", Enabled: true},
			{ID: "xopdeepseekv4flash", Name: "DeepSeek-V4-Flash", Enabled: true},
			{ID: "xopdeepseekv32", Name: "DeepSeek-V3.2", Enabled: true},
			{ID: "xopkimik26", Name: "Kimi-K2.6", Enabled: true},
			{ID: "xopkimik25", Name: "Kimi-K2.5", Enabled: true},
			{ID: "xminimaxm25", Name: "MiniMax-M2.5", Enabled: true},
			{ID: "xopqwen35397b", Name: "Qwen3.5-397B-A17B", Enabled: true},
			{ID: "xopqwen36v35b", Name: "Qwen3.6-35B-A3B", Enabled: true},
			{ID: "xopqwen35v35b", Name: "Qwen3.5-35B-A3B", Enabled: true},
			{ID: "xop3qwencodernext", Name: "Qwen3-Coder-Next-FP8", Enabled: true},
			{ID: "xopglmv47flash", Name: "GLM-4.7-Flash", Enabled: true},
		},
	},
}
