package main

// Preset provider definitions (22 platforms).
// These serve as defaults when no user config exists.

var presetProviders = []Provider{
	{
		ID: "openai", Name: "OpenAI", Type: "openai_compatible",
		BaseURL: "https://api.openai.com/v1",
		Priority: 10,
		Description: "OpenAI 官方 API",
		Icon: "openai",
		Models: []ModelDef{
			{"gpt-4o", "GPT-4o", true},
			{"gpt-4o-mini", "GPT-4o Mini", true},
			{"o1", "o1", true},
			{"o3", "o3", true},
			{"o4-mini", "o4-mini", true},
		},
	},
	{
		ID: "deepseek", Name: "DeepSeek", Type: "openai_compatible",
		BaseURL: "https://api.deepseek.com/v1",
		Priority: 5,
		Description: "深度求索 - 高性价比国产大模型",
		Icon: "deepseek",
		Models: []ModelDef{
			{"deepseek-chat", "DeepSeek Chat (V3)", true},
			{"deepseek-reasoner", "DeepSeek Reasoner (R1)", true},
		},
	},
	{
		ID: "qwen", Name: "通义千问", Type: "openai_compatible",
		BaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
		Priority: 5,
		Description: "阿里云通义千问",
		Icon: "qwen",
		Models: []ModelDef{
			{"qwen-turbo", "Qwen Turbo", true},
			{"qwen-plus", "Qwen Plus", true},
			{"qwen-max", "Qwen Max", true},
			{"qwen-long", "Qwen Long", true},
		},
	},
	{
		ID: "hunyuan", Name: "腾讯混元 (TokenHub)", Type: "openai_compatible",
		BaseURL: "https://api.hunyuan.cloud.tencent.com/v1",
		Priority: 3,
		Description: "腾讯云 TokenHub 大模型平台",
		Icon: "hunyuan",
		APIKeyURL: "https://console.cloud.tencent.com/tokenhub/apikey",
		Models: []ModelDef{
			{"hunyuan-turbos-latest", "混元 TurboS Latest", true},
			{"hy3-preview", "混元 Hy3 Preview", true},
			{"deepseek-v4-pro", "DeepSeek V4 Pro", true},
			{"deepseek-v4-flash", "DeepSeek V4 Flash", true},
			{"hunyuan-lite", "混元 Lite (免费)", true},
		},
	},
	{
		ID: "zhipu", Name: "智谱AI", Type: "openai_compatible",
		BaseURL: "https://open.bigmodel.cn/api/paas/v4",
		Priority: 5,
		Description: "智谱清言 GLM 系列",
		Icon: "zhipu",
		Models: []ModelDef{
			{"glm-4-plus", "GLM-4 Plus", true},
			{"glm-4", "GLM-4", true},
			{"glm-4-flash", "GLM-4 Flash (免费)", true},
			{"glm-4v-plus", "GLM-4V Plus (视觉)", true},
		},
	},
	{
		ID: "moonshot", Name: "Moonshot (Kimi)", Type: "openai_compatible",
		BaseURL: "https://api.moonshot.cn/v1",
		Priority: 5,
		Description: "月之暗面 Kimi",
		Icon: "moonshot",
		Models: []ModelDef{
			{"moonshot-v1-8k", "Moonshot V1 8K", true},
			{"moonshot-v1-32k", "Moonshot V1 32K", true},
			{"moonshot-v1-128k", "Moonshot V1 128K", true},
		},
	},
	{
		ID: "lingyiwanwu", Name: "零一万物", Type: "openai_compatible",
		BaseURL: "https://api.lingyiwanwu.com/v1",
		Priority: 5,
		Description: "零一万物 Yi 系列",
		Icon: "yi",
		Models: []ModelDef{
			{"yi-large", "Yi Large", true},
			{"yi-medium", "Yi Medium", true},
			{"yi-vision", "Yi Vision", true},
			{"yi-large-turbo", "Yi Large Turbo", true},
		},
	},
	{
		ID: "minimax", Name: "MiniMax", Type: "openai_compatible",
		BaseURL: "https://api.minimax.chat/v1",
		Priority: 5,
		Description: "MiniMax 大模型",
		Icon: "minimax",
		Models: []ModelDef{
			{"MiniMax-Text-01", "MiniMax Text 01", true},
			{"abab6.5s-chat", "abab6.5s Chat", true},
		},
	},
	{
		ID: "siliconflow", Name: "硅基流动", Type: "openai_compatible",
		BaseURL: "https://api.siliconflow.cn/v1",
		Priority: 5,
		Description: "硅基流动 - 开源模型聚合平台",
		Icon: "siliconflow",
		Models: []ModelDef{
			{"Qwen/Qwen2.5-72B-Instruct", "Qwen2.5 72B", true},
			{"deepseek-ai/DeepSeek-V3", "DeepSeek V3", true},
			{"deepseek-ai/DeepSeek-R1", "DeepSeek R1", true},
			{"meta-llama/Llama-3.3-70B-Instruct", "Llama 3.3 70B", true},
		},
	},
	{
		ID: "groq", Name: "Groq", Type: "openai_compatible",
		BaseURL: "https://api.groq.com/openai/v1",
		Priority: 5,
		Description: "Groq - 超快推理速度",
		Icon: "groq",
		Models: []ModelDef{
			{"llama-3.3-70b-versatile", "Llama 3.3 70B", true},
			{"llama-3.1-8b-instant", "Llama 3.1 8B", true},
			{"mixtral-8x7b-32768", "Mixtral 8x7B", true},
			{"gemma2-9b-it", "Gemma 2 9B", true},
		},
	},
	{
		ID: "xai", Name: "xAI (Grok)", Type: "openai_compatible",
		BaseURL: "https://api.x.ai/v1",
		Priority: 5,
		Description: "xAI Grok 系列",
		Icon: "xai",
		Models: []ModelDef{
			{"grok-2-latest", "Grok 2", true},
			{"grok-3", "Grok 3", true},
			{"grok-3-mini", "Grok 3 Mini", true},
		},
	},
	{
		ID: "together", Name: "Together AI", Type: "openai_compatible",
		BaseURL: "https://api.together.xyz/v1",
		Priority: 5,
		Description: "Together AI - 开源模型推理平台",
		Icon: "together",
		Models: []ModelDef{
			{"meta-llama/Llama-3.3-70B-Instruct-Turbo", "Llama 3.3 70B Turbo", true},
			{"deepseek-ai/DeepSeek-V3", "DeepSeek V3", true},
		},
	},
	{
		ID: "mistral", Name: "Mistral AI", Type: "openai_compatible",
		BaseURL: "https://api.mistral.ai/v1",
		Priority: 5,
		Description: "Mistral AI - 欧洲领先大模型",
		Icon: "mistral",
		Models: []ModelDef{
			{"mistral-large-latest", "Mistral Large", true},
			{"mistral-small-latest", "Mistral Small", true},
			{"codestral-latest", "Codestral", true},
			{"open-mistral-nemo", "Mistral Nemo", true},
		},
	},
	{
		ID: "doubao", Name: "火山引擎(豆包)", Type: "openai_compatible",
		BaseURL: "https://ark.cn-beijing.volces.com/api/v3",
		Priority: 5,
		Description: "字节跳动火山引擎豆包",
		Icon: "doubao",
		Models: []ModelDef{
			{"doubao-pro-32k", "豆包 Pro 32K", true},
			{"doubao-lite-32k", "豆包 Lite 32K", true},
		},
	},
	{
		ID: "spark", Name: "讯飞星火", Type: "openai_compatible",
		BaseURL: "https://spark-api-open.xf-yun.com/v1",
		Priority: 5,
		Description: "科大讯飞星火大模型",
		Icon: "spark",
		Models: []ModelDef{
			{"general", "讯飞星火 Lite", true},
			{"generalv3.5", "讯飞星火 Pro", true},
			{"generalv4", "讯飞星火 Max", true},
		},
	},
	{
		ID: "gemini", Name: "Google Gemini", Type: "openai_compatible",
		BaseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
		Priority: 4,
		Description: "Google Gemini - 多模态、超长上下文",
		Icon: "gemini",
		APIKeyURL: "https://aistudio.google.com/apikey",
		Models: []ModelDef{
			{"gemini-2.5-pro", "Gemini 2.5 Pro", true},
			{"gemini-2.5-flash", "Gemini 2.5 Flash", true},
			{"gemini-2.0-flash", "Gemini 2.0 Flash", true},
			{"gemini-2.0-flash-lite", "Gemini 2.0 Flash Lite", true},
			{"gemini-1.5-pro", "Gemini 1.5 Pro", true},
			{"gemini-1.5-flash", "Gemini 1.5 Flash", true},
		},
	},
	{
		ID: "openrouter", Name: "OpenRouter", Type: "openai_compatible",
		BaseURL: "https://openrouter.ai/api/v1",
		Priority: 20,
		Description: "OpenRouter - 全球模型聚合平台",
		Icon: "openrouter",
		Models: []ModelDef{
			{"openai/gpt-4o", "GPT-4o (via OpenRouter)", true},
			{"anthropic/claude-sonnet-4", "Claude Sonnet 4 (via OpenRouter)", true},
			{"deepseek/deepseek-chat", "DeepSeek Chat (via OpenRouter)", true},
			{"meta-llama/llama-3.3-70b-instruct", "Llama 3.3 70B (via OpenRouter)", true},
		},
	},
	{
		ID: "poe", Name: "Poe", Type: "openai_compatible",
		BaseURL: "https://api.poe.com/v1",
		Priority: 15,
		Description: "Poe (Quora) - 多模型聚合平台",
		Icon: "poe",
		Models: []ModelDef{
			{"GPT-4o", "GPT-4o", true},
			{"Claude-3.5-Sonnet", "Claude 3.5 Sonnet", true},
			{"Gemini-1.5-Pro", "Gemini 1.5 Pro", true},
			{"DeepSeek-V3", "DeepSeek V3", true},
			{"Llama-3.3-70B", "Llama 3.3 70B", true},
		},
	},
	{
		ID: "sid", Name: "SID.ai (开发者平台)", Type: "openai_compatible",
		BaseURL: "https://api.sid.ai/v1",
		Priority: 15,
		Description: "SID.ai 开发者平台 - 兼容 OpenAI API",
		Icon: "sider",
		APIKeyURL: "https://dashboard.sid.ai",
		Models: []ModelDef{
			{"gpt-4o", "GPT-4o", true},
			{"gpt-4o-mini", "GPT-4o Mini", true},
			{"claude-3-5-sonnet", "Claude 3.5 Sonnet", true},
		},
	},
	{
		ID: "sider", Name: "Sider.ai (网页版)", Type: "sider",
		BaseURL: "https://sider.ai",
		Priority: 2,
		Description: "Sider.ai 网页版 - 需登录获取 Token",
		Icon: "sider",
		APIKeyURL: "https://sider.ai",
		Models: []ModelDef{
			{"gpt-4o-mini", "GPT-4o Mini", true},
			{"gpt-4o", "GPT-4o (高级)", true},
			{"claude-3.5-haiku", "Claude 3.5 Haiku", true},
			{"claude-3.5-sonnet", "Claude 3.5 Sonnet (高级)", true},
			{"gemini-2.0-flash", "Gemini 2.0 Flash", true},
			{"deepseek-chat", "DeepSeek V3", true},
			{"deepseek-reasoner", "DeepSeek R1 (高级)", true},
		},
	},
	{
		ID: "ollama", Name: "Ollama (本地)", Type: "openai_compatible",
		BaseURL: "http://localhost:11434/v1",
		APIKey: "ollama",
		Priority: 50,
		Description: "本地部署模型",
		Icon: "ollama",
		Models: []ModelDef{
			{"llama3.2", "Llama 3.2", true},
			{"qwen2.5", "Qwen 2.5", true},
			{"deepseek-r1", "DeepSeek R1", true},
		},
	},
	{
		ID: "coze", Name: "扣子 (Coze)", Type: "coze",
		BaseURL: "https://api.coze.cn",
		Priority: 1,
		Description: "扣子智能体平台（专有 API，模型为 coze-{bot_id} 格式）",
		Icon: "coze",
		Models: []ModelDef{},
	},
}
