package main

// Preset provider definitions (35 platforms).
// These serve as defaults when no user config exists.

var presetProviders = []Provider{
	{
		ID: "openai", Name: "OpenAI", Type: "openai_compatible",
		BaseURL: "https://api.openai.com/v1",
		Priority: 10,
		Description: "OpenAI 官方 API",
		Icon: "openai",
		Models: []ModelDef{
			{"gpt-4o", "GPT-4o", true},
			{"gpt-4o-mini", "GPT-4o Mini", true},
			{"o1", "o1", true},
			{"o3", "o3", true},
			{"o4-mini", "o4-mini", true},
		},
	},
	{
		ID: "deepseek", Name: "DeepSeek", Type: "openai_compatible",
		BaseURL: "https://api.deepseek.com/v1",
		Priority: 5,
		Description: "深度求索 - 高性价比国产大模型",
		Icon: "deepseek",
		Models: []ModelDef{
			{"deepseek-chat", "DeepSeek Chat (V3)", true},
			{"deepseek-reasoner", "DeepSeek Reasoner (R1)", true},
		},
	},
	{
		ID: "qwen", Name: "通义千问", Type: "openai_compatible",
		BaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
		Priority: 5,
		Description: "阿里云通义千问",
		Icon: "qwen",
		Models: []ModelDef{
			{"qwen-turbo", "Qwen Turbo", true},
			{"qwen-plus", "Qwen Plus", true},
			{"qwen-max", "Qwen Max", true},
			{"qwen-long", "Qwen Long", true},
		},
	},
	{
		ID: "tokenhub-coding", Name: "腾讯 TokenHub Coding Plan", Type: "openai_compatible",
		BaseURL: "https://api.lkeap.cloud.tencent.com/coding/v3",
		Priority: 3,
		Description: "腾讯 TokenHub 编程套餐（按请求次数，5h/周/月限额），API Key 格式 sk-sp-xxxx",
		Icon: "hunyuan",
		APIKeyURL: "https://console.cloud.tencent.com/tokenhub/codingplan",
		Models: []ModelDef{
			{"tc-code-latest", "Auto 智能路由", true},
			{"glm-5", "GLM-5", true},
			{"minimax-m2.5", "MiniMax M2.5", true},
			{"kimi-k2.5", "Kimi K2.5", true},
		},
	},
	{
		ID: "tokenhub-plan", Name: "腾讯 TokenHub Token Plan", Type: "openai_compatible",
		BaseURL: "https://api.lkeap.cloud.tencent.com/plan/v3",
		Priority: 3,
		Description: "腾讯 TokenPlan 个人版（按 Token 计费，订阅制），API Key 格式 sk-tp-xxxx",
		Icon: "hunyuan",
		APIKeyURL: "https://console.cloud.tencent.com/tokenhub/tokenplan",
		Models: []ModelDef{
			{"tc-code-latest", "Auto 智能路由", true},
			{"glm-5", "GLM-5", true},
			{"glm-5.1", "GLM-5.1", true},
			{"minimax-m2.5", "MiniMax M2.5", true},
			{"minimax-m2.7", "MiniMax M2.7", true},
			{"kimi-k2.5", "Kimi K2.5", true},
			{"deepseek-v4-flash-202605", "DeepSeek V4 Flash 原厂直供", true},
			{"deepseek-v4-pro-202606", "DeepSeek V4 Pro 原厂直供", true},
			{"hy3-preview", "Hy3 Preview (混元)", true},
		},
	},
	{
		ID: "tokenhub-enterprise", Name: "腾讯 TokenHub 企业版", Type: "openai_compatible",
		BaseURL: "https://tokenhub.tencentmaas.com/plan/v3",
		Priority: 3,
		Description: "腾讯 TokenPlan 企业版（积分制，多 Key 配额管理，团队共享）",
		Icon: "hunyuan",
		APIKeyURL: "https://console.cloud.tencent.com/tokenhub/tokenplan-e",
		Models: []ModelDef{
			{"auto", "Auto 智能路由", true},
			{"glm-5", "GLM-5", true},
			{"glm-5.1", "GLM-5.1", true},
			{"glm-5.2", "GLM-5.2", true},
			{"glm-5-turbo", "GLM-5 Turbo", true},
			{"minimax-m2.5", "MiniMax M2.5", true},
			{"minimax-m2.7", "MiniMax M2.7", true},
			{"minimax-m3", "MiniMax M3", true},
			{"kimi-k2.5", "Kimi K2.5", true},
			{"kimi-k2.6", "Kimi K2.6", true},
			{"deepseek-v4-flash", "DeepSeek V4 Flash", true},
			{"deepseek-v4-pro", "DeepSeek V4 Pro", true},
			{"deepseek-v4-flash-202605", "DeepSeek V4 Flash 原厂直供", true},
			{"deepseek-v4-pro-202606", "DeepSeek V4 Pro 原厂直供", true},
		},
	},
	{
		ID: "zhipu", Name: "智谱AI", Type: "openai_compatible",
		BaseURL: "https://open.bigmodel.cn/api/paas/v4",
		Priority: 5,
		Description: "智谱清言 GLM 系列",
		Icon: "zhipu",
		Models: []ModelDef{
			{"glm-4-plus", "GLM-4 Plus", true},
			{"glm-4", "GLM-4", true},
			{"glm-4-flash", "GLM-4 Flash (免费)", true},
			{"glm-4v-plus", "GLM-4V Plus (视觉)", true},
		},
	},
	{
		ID: "moonshot", Name: "Moonshot (Kimi)", Type: "openai_compatible",
		BaseURL: "https://api.moonshot.cn/v1",
		Priority: 5,
		Description: "月之暗面 Kimi",
		Icon: "moonshot",
		Models: []ModelDef{
			{"moonshot-v1-8k", "Moonshot V1 8K", true},
			{"moonshot-v1-32k", "Moonshot V1 32K", true},
			{"moonshot-v1-128k", "Moonshot V1 128K", true},
		},
	},
	{
		ID: "lingyiwanwu", Name: "零一万物", Type: "openai_compatible",
		BaseURL: "https://api.lingyiwanwu.com/v1",
		Priority: 5,
		Description: "零一万物 Yi 系列",
		Icon: "yi",
		Models: []ModelDef{
			{"yi-large", "Yi Large", true},
			{"yi-medium", "Yi Medium", true},
			{"yi-vision", "Yi Vision", true},
			{"yi-large-turbo", "Yi Large Turbo", true},
		},
	},
	{
		ID: "minimax", Name: "MiniMax", Type: "openai_compatible",
		BaseURL: "https://api.minimax.chat/v1",
		Priority: 5,
		Description: "MiniMax 大模型",
		Icon: "minimax",
		Models: []ModelDef{
			{"MiniMax-Text-01", "MiniMax Text 01", true},
			{"abab6.5s-chat", "abab6.5s Chat", true},
		},
	},
	{
		ID: "siliconflow", Name: "硅基流动", Type: "openai_compatible",
		BaseURL: "https://api.siliconflow.cn/v1",
		Priority: 5,
		Description: "硅基流动 - 开源模型聚合平台",
		Icon: "siliconflow",
		Models: []ModelDef{
			{"Qwen/Qwen2.5-72B-Instruct", "Qwen2.5 72B", true},
			{"deepseek-ai/DeepSeek-V3", "DeepSeek V3", true},
			{"deepseek-ai/DeepSeek-R1", "DeepSeek R1", true},
			{"meta-llama/Llama-3.3-70B-Instruct", "Llama 3.3 70B", true},
		},
	},
	{
		ID: "groq", Name: "Groq", Type: "openai_compatible",
		BaseURL: "https://api.groq.com/openai/v1",
		Priority: 5,
		Description: "Groq - 超快推理速度",
		Icon: "groq",
		Models: []ModelDef{
			{"llama-3.3-70b-versatile", "Llama 3.3 70B", true},
			{"llama-3.1-8b-instant", "Llama 3.1 8B", true},
			{"mixtral-8x7b-32768", "Mixtral 8x7B", true},
			{"gemma2-9b-it", "Gemma 2 9B", true},
		},
	},
	{
		ID: "xai", Name: "xAI (Grok)", Type: "openai_compatible",
		BaseURL: "https://api.x.ai/v1",
		Priority: 5,
		Description: "xAI Grok 系列",
		Icon: "xai",
		Models: []ModelDef{
			{"grok-2-latest", "Grok 2", true},
			{"grok-3", "Grok 3", true},
			{"grok-3-mini", "Grok 3 Mini", true},
		},
	},
	{
		ID: "together", Name: "Together AI", Type: "openai_compatible",
		BaseURL: "https://api.together.xyz/v1",
		Priority: 5,
		Description: "Together AI - 开源模型推理平台",
		Icon: "together",
		Models: []ModelDef{
			{"meta-llama/Llama-3.3-70B-Instruct-Turbo", "Llama 3.3 70B Turbo", true},
			{"deepseek-ai/DeepSeek-V3", "DeepSeek V3", true},
		},
	},
	{
		ID: "mistral", Name: "Mistral AI", Type: "openai_compatible",
		BaseURL: "https://api.mistral.ai/v1",
		Priority: 5,
		Description: "Mistral AI - 欧洲领先大模型",
		Icon: "mistral",
		Models: []ModelDef{
			{"mistral-large-latest", "Mistral Large", true},
			{"mistral-small-latest", "Mistral Small", true},
			{"codestral-latest", "Codestral", true},
			{"open-mistral-nemo", "Mistral Nemo", true},
		},
	},
	{
		ID: "doubao", Name: "火山引擎(豆包)", Type: "openai_compatible",
		BaseURL: "https://ark.cn-beijing.volces.com/api/v3",
		Priority: 5,
		Description: "字节跳动火山引擎豆包",
		Icon: "doubao",
		Models: []ModelDef{
			{"doubao-pro-32k", "豆包 Pro 32K", true},
			{"doubao-lite-32k", "豆包 Lite 32K", true},
		},
	},
	{
		ID: "spark", Name: "讯飞星火", Type: "openai_compatible",
		BaseURL: "https://spark-api-open.xf-yun.com/v1",
		Priority: 5,
		Description: "科大讯飞星火大模型",
		Icon: "spark",
		Models: []ModelDef{
			{"general", "讯飞星火 Lite", true},
			{"generalv3.5", "讯飞星火 Pro", true},
			{"generalv4", "讯飞星火 Max", true},
		},
	},
	{
		ID: "gemini", Name: "Google Gemini", Type: "openai_compatible",
		BaseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
		Priority: 4,
		Description: "Google Gemini - 多模态、超长上下文",
		Icon: "gemini",
		APIKeyURL: "https://aistudio.google.com/apikey",
		Models: []ModelDef{
			{"gemini-2.5-pro", "Gemini 2.5 Pro", true},
			{"gemini-2.5-flash", "Gemini 2.5 Flash", true},
			{"gemini-2.0-flash", "Gemini 2.0 Flash", true},
			{"gemini-2.0-flash-lite", "Gemini 2.0 Flash Lite", true},
			{"gemini-1.5-pro", "Gemini 1.5 Pro", true},
			{"gemini-1.5-flash", "Gemini 1.5 Flash", true},
		},
	},
	{
		ID: "openrouter", Name: "OpenRouter", Type: "openai_compatible",
		BaseURL: "https://openrouter.ai/api/v1",
		Priority: 20,
		Description: "OpenRouter - 全球模型聚合平台",
		Icon: "openrouter",
		Models: []ModelDef{
			{"openai/gpt-4o", "GPT-4o (via OpenRouter)", true},
			{"anthropic/claude-sonnet-4", "Claude Sonnet 4 (via OpenRouter)", true},
			{"deepseek/deepseek-chat", "DeepSeek Chat (via OpenRouter)", true},
			{"meta-llama/llama-3.3-70b-instruct", "Llama 3.3 70B (via OpenRouter)", true},
		},
	},
	{
		ID: "poe", Name: "Poe", Type: "openai_compatible",
		BaseURL: "https://api.poe.com/v1",
		Priority: 15,
		Description: "Poe (Quora) - 多模型聚合平台",
		Icon: "poe",
		Models: []ModelDef{
			{"GPT-4o", "GPT-4o", true},
			{"Claude-3.5-Sonnet", "Claude 3.5 Sonnet", true},
			{"Gemini-1.5-Pro", "Gemini 1.5 Pro", true},
			{"DeepSeek-V3", "DeepSeek V3", true},
			{"Llama-3.3-70B", "Llama 3.3 70B", true},
		},
	},
	{
		ID: "sid", Name: "SID.ai (开发者平台)", Type: "openai_compatible",
		BaseURL: "https://api.sid.ai/v1",
		Priority: 15,
		Description: "SID.ai 开发者平台 - 兼容 OpenAI API",
		Icon: "sider",
		APIKeyURL: "https://dashboard.sid.ai",
		Models: []ModelDef{
			{"gpt-4o", "GPT-4o", true},
			{"gpt-4o-mini", "GPT-4o Mini", true},
			{"claude-3-5-sonnet", "Claude 3.5 Sonnet", true},
		},
	},
	{
		ID: "sider", Name: "Sider.ai (网页版)", Type: "sider",
		BaseURL: "https://sider.ai",
		Priority: 2,
		Description: "Sider.ai 网页版聚合平台。API Key 填写浏览器扩展登录后的 Session Token（F12→Cookies→token字段）",
		Icon: "sider",
		APIKeyURL: "https://sider.ai",
		Models: []ModelDef{
			{"gpt-4o-mini", "GPT-4o Mini", true},
			{"gpt-4o", "GPT-4o (高级)", true},
			{"claude-3.5-haiku", "Claude 3.5 Haiku", true},
			{"claude-3.5-sonnet", "Claude 3.5 Sonnet (高级)", true},
			{"gemini-2.0-flash", "Gemini 2.0 Flash", true},
			{"deepseek-chat", "DeepSeek V3", true},
			{"deepseek-reasoner", "DeepSeek R1 (高级)", true},
		},
	},
	{
		ID: "ollama", Name: "Ollama (本地)", Type: "openai_compatible",
		BaseURL: "http://localhost:11434/v1",
		APIKey: "ollama",
		Priority: 50,
		Description: "本地部署模型",
		Icon: "ollama",
		Models: []ModelDef{
			{"llama3.2", "Llama 3.2", true},
			{"qwen2.5", "Qwen 2.5", true},
			{"deepseek-r1", "DeepSeek R1", true},
		},
	},
	{
		ID: "coze", Name: "扣子 (Coze)", Type: "coze",
		BaseURL: "https://api.coze.cn",
		Priority: 1,
		Description: "扣子智能体平台（专有 API，模型为 coze-{bot_id} 格式）。API Key 填写 PAT 个人访问令牌",
		APIKeyURL:  "https://www.coze.cn",
		Icon: "coze",
		Models: []ModelDef{},
	},
	{
		ID: "nvidia", Name: "NVIDIA NIM", Type: "openai_compatible",
		BaseURL:    "https://integrate.api.nvidia.com/v1",
		Priority:   4,
		Description: "NVIDIA 推理微服务平台，100+ 开源模型免费调用（40 RPM），OpenAI 兼容",
		Icon:        "nvidia",
		APIKeyURL:   "https://build.nvidia.com/",
		Models: []ModelDef{
			{ID: "meta/llama-4-maverick-17b-128e-instruct", Name: "Llama 4 Maverick"},
			{ID: "minimaxai/minimax-m2.7", Name: "MiniMax M2.7"},
			{ID: "deepseek-ai/deepseek-v3.2", Name: "DeepSeek V3.2"},
			{ID: "deepseek-ai/deepseek-r1-distill-llama-8b", Name: "DeepSeek R1 Distill"},
			{ID: "qwen/qwen3.5-397b-a17b", Name: "Qwen 3.5 397B"},
			{ID: "qwen/qwen3-coder-480b", Name: "Qwen3 Coder 480B"},
			{ID: "moonshotai/kimi-k2.6", Name: "Kimi K2.6"},
			{ID: "z-ai/glm-5.1", Name: "GLM 5.1"},
			{ID: "mistralai/mistral-large-3", Name: "Mistral Large 3"},
			{ID: "stepfun-ai/step-3.5-flash", Name: "Step-3.5 Flash"},
			{ID: "nvidia/nemotron-3-nano-30b-a3b", Name: "Nemotron 3 Nano"},
			{ID: "meta/llama-3.1-70b-instruct", Name: "Llama 3.1 70B"},
			{ID: "google/gemma-3n-e4b", Name: "Gemma 3n E4B"},
			{ID: "mistralai/mistral-nemotron", Name: "Mistral Nemotron"},
		},
	},
	{
		ID: "anthropic", Name: "Anthropic Claude", Type: "anthropic",
		BaseURL:    "https://api.anthropic.com",
		Priority:   2,
		Description: "Claude 系列模型（专有 Messages API，系统自动适配）。API Key 填写 Anthropic API Key（sk-ant-xxx）",
		Icon:        "anthropic",
		APIKeyURL:   "https://console.anthropic.com/",
		Models: []ModelDef{
			{ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4"},
			{ID: "claude-3-5-sonnet-20241022", Name: "Claude 3.5 Sonnet"},
			{ID: "claude-3-5-haiku-20241022", Name: "Claude 3.5 Haiku"},
			{ID: "claude-3-opus-20240229", Name: "Claude 3 Opus"},
			{ID: "claude-3-haiku-20240307", Name: "Claude 3 Haiku"},
		},
	},
	{
		ID: "qianfan", Name: "百度千帆", Type: "openai_compatible",
		BaseURL:    "https://qianfan.baidubce.com/v2",
		Priority:   5,
		Description: "百度智能云千帆平台，ERNIE 文心系列 + 第三方模型",
		Icon:        "qianfan",
		APIKeyURL:   "https://qianfan.cloud.baidu.com",
		Models: []ModelDef{
			{ID: "ernie-4.5-turbo-32k", Name: "ERNIE 4.5 Turbo"},
			{ID: "ernie-4.0-turbo-8k", Name: "ERNIE 4.0 Turbo"},
			{ID: "ernie-speed-128k", Name: "ERNIE Speed 128K"},
			{ID: "deepseek-r1-distill-qwen-32b", Name: "DeepSeek R1 Distill Qwen 32B"},
		},
	},
	{
		ID: "novita", Name: "Novita AI", Type: "openai_compatible",
		BaseURL:    "https://api.novita.ai/v3/openai",
		Priority:   5,
		Description: "聚合平台，200+ 开源模型，价格低廉，OpenAI 兼容",
		Icon:        "novita",
		APIKeyURL:   "https://novita.ai/",
		Models: []ModelDef{
			{ID: "deepseek/deepseek-r1", Name: "DeepSeek R1"},
			{ID: "deepseek/deepseek-v3", Name: "DeepSeek V3"},
			{ID: "qwen/qwen-3-235b-a22b", Name: "Qwen 3 235B"},
			{ID: "meta-llama/llama-4-maverick-17b-128e-instruct", Name: "Llama 4 Maverick"},
			{ID: "meta-llama/llama-3.3-70b-instruct", Name: "Llama 3.3 70B"},
		},
	},
	{
		ID: "fireworks", Name: "Fireworks AI", Type: "openai_compatible",
		BaseURL:    "https://api.fireworks.ai/inference/v1",
		Priority:   5,
		Description: "高速推理平台，开源模型优化，OpenAI 兼容",
		Icon:        "fireworks",
		APIKeyURL:   "https://fireworks.ai/account/api-keys",
		Models: []ModelDef{
			{ID: "accounts/fireworks/models/deepseek-v3", Name: "DeepSeek V3"},
			{ID: "accounts/fireworks/models/deepseek-r1", Name: "DeepSeek R1"},
			{ID: "accounts/fireworks/models/qwen3-235b-a22b", Name: "Qwen 3 235B"},
			{ID: "accounts/fireworks/models/llama4-maverick-instruct-basic", Name: "Llama 4 Maverick"},
			{ID: "accounts/fireworks/models/llama-v3p3-70b-instruct", Name: "Llama 3.3 70B"},
		},
	},
	{
		ID: "cohere", Name: "Cohere", Type: "openai_compatible",
		BaseURL:    "https://api.cohere.com/compatibility/v1",
		Priority:   5,
		Description: "企业级 NLP 平台，Command R+ 系列，OpenAI 兼容",
		Icon:        "cohere",
		APIKeyURL:   "https://dashboard.cohere.com/api-keys",
		Models: []ModelDef{
			{ID: "command-r-plus-08-2024", Name: "Command R+"},
			{ID: "command-r-08-2024", Name: "Command R"},
			{ID: "command-a-03-2025", Name: "Command A"},
		},
	},
	{
		ID: "cerebras", Name: "Cerebras", Type: "openai_compatible",
		BaseURL:    "https://api.cerebras.ai/v1",
		Priority:   4,
		Description: "极致推理速度（Llama 系列），适合延迟敏感场景，OpenAI 兼容",
		Icon:        "cerebras",
		APIKeyURL:   "https://cloud.cerebras.ai/",
		Models: []ModelDef{
			{ID: "llama-3.3-70b", Name: "Llama 3.3 70B"},
			{ID: "llama-3.1-8b", Name: "Llama 3.1 8B"},
			{ID: "llama3.1-8b", Name: "Llama 3.1 8B (alt)"},
		},
	},
	{
		ID: "stepfun", Name: "阶跃星辰", Type: "openai_compatible",
		BaseURL:    "https://api.stepfun.com/v1",
		Priority:   5,
		Description: "Step 系列模型，多模态与推理能力均衡，OpenAI 兼容",
		Icon:        "stepfun",
		APIKeyURL:   "https://platform.stepfun.com/",
		Models: []ModelDef{
			{ID: "step-2-16k", Name: "Step-2 16K"},
			{ID: "step-1.5v-mini", Name: "Step-1.5V Mini"},
			{ID: "step-1-128k", Name: "Step-1 128K"},
			{ID: "step-1-8k", Name: "Step-1 8K"},
		},
	},
	{
		ID: "baichuan", Name: "百川智能", Type: "openai_compatible",
		BaseURL:    "https://api.baichuan-ai.com/v1",
		Priority:   5,
		Description: "Baichuan 系列模型，中文能力强，企业场景优化，OpenAI 兼容",
		Icon:        "baichuan",
		APIKeyURL:   "https://platform.baichuan-ai.com/",
		Models: []ModelDef{
			{ID: "Baichuan4-Turbo", Name: "Baichuan 4 Turbo"},
			{ID: "Baichuan4-Air", Name: "Baichuan 4 Air"},
			{ID: "Baichuan4", Name: "Baichuan 4"},
			{ID: "Baichuan3-Turbo", Name: "Baichuan 3 Turbo"},
		},
	},
	{
		ID: "agnes", Name: "Agnes AI", Type: "openai_compatible",
		BaseURL:    "https://apihub.agnes-ai.com/v1",
		Priority:   5,
		Description: "新加坡 Sapiens AI 多模态平台（文本/图像/视频），OpenAI 兼容，注册即送免费额度",
		Icon:        "agnes",
		APIKeyURL:   "https://platform.agnes-ai.com/",
		Models: []ModelDef{
			{ID: "agnes-2.0-flash", Name: "Agnes 2.0 Flash (文本)"},
			{ID: "agnes-image-2.1-flash", Name: "Agnes Image 2.1 Flash (图像)"},
			{ID: "agnes-image-2.0-flash", Name: "Agnes Image 2.0 Flash (图像)"},
			{ID: "agnes-video-v2.0", Name: "Agnes Video V2.0 (视频)"},
		},
	},
	{
		ID: "aihubmix", Name: "AIHubMix", Type: "openai_compatible",
		BaseURL:    "https://aihubmix.com/v1",
		Priority:   5,
		Description: "聚合平台，提供免费额度，OpenAI 兼容 API",
		Icon:        "aihubmix",
		APIKeyURL:   "https://aihubmix.com/",
		Models: []ModelDef{
			{ID: "gpt-4o", Name: "GPT-4o"},
			{ID: "claude-3.5-sonnet", Name: "Claude 3.5 Sonnet"},
			{ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash"},
		},
	},
	{
		ID: "lmstudio-local", Name: "LM Studio (本地)", Type: "openai_compatible",
		BaseURL:    "http://localhost:1234/v1",
		Priority:   1,
		Description: "LM Studio 本地模型推理，OpenAI 兼容 API",
		Icon:        "lmstudio",
		APIKeyURL:   "https://lmstudio.ai/",
		Models: []ModelDef{
			{ID: "local-model", Name: "本地模型（自动加载）"},
		},
	},
}
